# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68184d44f3d210ef4b3ac3c10505b9cbb48d72d1b86c0555bcb62f63fdc0532c4e7002a2f2eb854a9adf6e1227cb3644295e2a3e73e9d03c538a396575b703b7

test:
  secret_key_base: 5c5c3acc0f91724b1a1aac54eece04b2a5f145c4d28471f09aa189f05e3ee7932a7dd2b7f2146f9c7fc9d64693ca9fa1a5777f8c3e57071aec6efc2245440a20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
